// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahxyctxsluvzfwovtayh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeHljdHhzbHV2emZ3b3Z0YXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzYyNDksImV4cCI6MjA3MjIxMjI0OX0.dVnT6yuTHbNEpbel7ltCGllX24k9DMqpoR2m384jteY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});